"use strict";
exports.__esModule = true;
var Conta_1 = require("./classes/Conta");
var Cliente_1 = require("./classes/Cliente");
var cliente = new Cliente_1.Cliente();
cliente.nome = "Majo Silva";
cliente.cpf = "123.123.123.23";
cliente.email = "meu.email@gmail.com";
var conta1 = new Conta_1.Conta(cliente, "254", "5667", 0);
var conta2 = new Conta_1.Conta(cliente, "333", "5678", 0);
console.log(conta1.getSaldo());
console.log(conta2.getSaldo());
conta1.depositar(10000);
console.log(conta1.getSaldo());
conta1.sacar(100);
console.log(conta1.getSaldo());
conta1.transferir(200, conta2);
console.log(conta1.getSaldo());
console.log(conta2.getSaldo());
